# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nplieger <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/19 14:27:18 by nplieger          #+#    #+#              #
#    Updated: 2023/09/19 18:58:53 by nplieger         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
version: '3.8'

# Services #
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - inception

# Networks #
networks:
  inception:
    driver: bridge
