# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nplieger <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/19 14:27:18 by nplieger          #+#    #+#              #
#    Updated: 2023/09/19 18:58:53 by nplieger         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
version: '3.8'

# Services #
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - inception


# Volumes #
volumes:
  wordpress_data:

# Networks #
networks:
  inception:
    driver: bridge
