# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nicolas <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/21 14:46:20 by nicolas           #+#    #+#              #
#    Updated: 2023/10/05 12:44:02 by nicolas          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
# Latest version as of 21 september 2023
version: '3.8'

# Networks
networks:
  inception:
    driver: bridge

# Volumes
volumes:
  website_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/website
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

# Services
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        NGINX_CERTS: ${NGINX_CERTS}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - website_data:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        DB_TITLE: ${DB_TITLE}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
        DB_TITLE: ${DB_TITLE}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_HOST: ${DB_HOST}
        HTML_PATH: ${HTML_PATH}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - website_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis

# **************************************************************************** #
# *                                   BONUS                                  * #
# **************************************************************************** #

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception

  ftp-server:
    container_name: ftp-server
    build:
      context: ./requirements/bonus/ftp-server
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        FTP_CERTS: ${FTP_CERTS}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - website_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      args:
        HTML_PATH: ${HTML_PATH}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - website_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
