# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nicolas <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/21 14:46:20 by nicolas           #+#    #+#              #
#    Updated: 2023/09/26 11:03:59 by nplieger         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
# Latest version as of 21 september 2023
version: '3.8'

# Networks
networks:
  inception:
    driver: bridge

# Volumes
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${APP_USER}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${APP_USER}/data/mariadb
      o: bind

# Services
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERTS_: ${CERTS_}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        DB_TITLE: ${DB_TITLE}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
        DB_TITLE: ${DB_TITLE}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_HOST: ${DB_HOST}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
